<?php

namespace SayHello\Theme\Controller;

/**
 * Assets (CSS, JavaScript etc)
 *
 * @author Mark Howells-Mead <mark@sayhello.ch>
 */
class Assets
{

	/**
	 * Runs the controller
	 *
	 * @return void
	 */
	public function run(): void
	{
		add_action('enqueue_block_assets', [$this, 'registerFrontendAssets']);
	}

	/**
	 * Registers assets for the frontend only
	 *
	 * @return void
	 */
	public function registerFrontendAssets(): void
	{

		if (!is_user_logged_in()) {
			wp_deregister_style('dashicons');
		}

		if (is_admin()) {
			return;
		}

		$min = defined('WP_DEBUG') && WP_DEBUG === false;

		// CSS. Make sure that the block library CSS is loaded first.
		$deps = ['wp-block-library'];

		wp_enqueue_style('sht-style', get_template_directory_uri() . '/assets/styles/ui' . ($min ? '.min' : '') . '.css', $deps, filemtime(get_template_directory() . '/assets/styles/ui' . ($min ? '.min' : '') . '.css'));

		// Javascript is always minified. Dependencies and version come from the file generated by webpack.
		$script_asset_path = get_template_directory() . '/assets/scripts/ui.asset.php';
		$script_asset = file_exists($script_asset_path) ? require($script_asset_path) : ['dependencies' => [], 'version' => filemtime(get_template_directory() . '/assets/scripts/ui.js')];

		wp_enqueue_script('sht-script', get_template_directory_uri() . '/assets/scripts/ui.js', $script_asset['dependencies'], $script_asset['version'], true);
		wp_localize_script('sht-script', 'sht_theme', [
			'directory_uri' => get_template_directory_uri(),
			'version' => wp_get_theme()->get('Version'),
			'environment' => wp_get_environment_type(),
		]);
	}
}
